version: 2
updates:
  # Maven dependencies (backend)
  - package-ecosystem: "maven"
    directory: "/server"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    reviewers:
      - "sarangsalgi-team"
    assignees:
      - "sarangsalgi-team"
    commit-message:
      prefix: "deps"
      prefix-development: "deps-dev"
      include: "scope"

  # npm dependencies (frontend)
  - package-ecosystem: "npm"
    directory: "/client"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    reviewers:
      - "sarangsalgi-team"
    assignees:
      - "sarangsalgi-team"
    commit-message:
      prefix: "deps"
      prefix-development: "deps-dev"
      include: "scope"

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    reviewers:
      - "sarangsalgi-team"
    assignees:
      - "sarangsalgi-team"