version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: sarangsalgi-postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-sarangsalgi}
      POSTGRES_USER: ${POSTGRES_USER:-sarangsalgi}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-sarangsalgi123}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U sarangsalgi"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: