spring:
  application:
    name: sarangsalgi
  
  profiles:
    active: dev
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 8080

# OpenAPI Documentation
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

# Admin Configuration
sarangsalgi:
  admin:
    password: ${ADMIN_PASSWORD:admin123}

---
# Development Profile (H2)
spring:
  config:
    activate:
      on-profile: dev
  
  datasource:
    url: jdbc:h2:file:./data/sarangsalgi;AUTO_SERVER=TRUE
    driverClassName: org.h2.Driver
    username: sa
    password: 
  
  h2:
    console:
      enabled: true
      path: /h2-console

---
# Production Profile (PostgreSQL)
spring:
  config:
    activate:
      on-profile: prod
  
  datasource:
    url: jdbc:postgresql://localhost:5432/sarangsalgi
    username: sarangsalgi
    password: sarangsalgi123
    driver-class-name: org.postgresql.Driver
  
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect